import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname } from 'path';

// Paths
const PACKAGE_JSON_PATH = 'package.json';
const TAURI_CONF_PATH = 'src-tauri/tauri.conf.json';
const CARGO_TOML_PATH = 'src-tauri/Cargo.toml';
const GENERATED_UPDATER_PATH = 'src/generated/updater.ts';
const DEFAULT_OWNER_REPO = 'yq6666-66/codex-clone-launcher';

function writeTextIfChanged(path, content) {
  let current = '';
  try {
    current = readFileSync(path, 'utf-8');
  } catch {
    // File does not exist yet.
  }
  if (current === content) return false;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  return true;
}

function normalizeOwnerRepo(value) {
  const cleaned = String(value || '').trim();
  if (!cleaned) return '';
  const match = cleaned.match(/github\.com[:/]+([^/\s]+)\/([^/\s#.]+)(?:\.git)?/i);
  if (match) return `${match[1]}/${match[2].replace(/\.git$/i, '')}`;
  if (/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(cleaned)) return cleaned;
  return '';
}

function packageRepositoryUrl(packageJson) {
  const repository = packageJson.repository;
  if (typeof repository === 'string') return repository;
  if (repository && typeof repository.url === 'string') return repository.url;
  return '';
}

function resolveUpdaterConfig(packageJson) {
  const endpointFromEnv = String(process.env.UPDATER_ENDPOINT || '').trim();
  const ownerRepo =
    normalizeOwnerRepo(process.env.UPDATER_OWNER_REPO) ||
    normalizeOwnerRepo(process.env.GITHUB_REPOSITORY) ||
    normalizeOwnerRepo(packageRepositoryUrl(packageJson)) ||
    DEFAULT_OWNER_REPO;
  const endpoint =
    endpointFromEnv || `https://github.com/${ownerRepo}/releases/latest/download/latest.json`;
  const releasePage =
    String(process.env.UPDATER_RELEASE_PAGE || '').trim() ||
    `https://github.com/${ownerRepo}/releases/latest`;
  return { ownerRepo, endpoint, releasePage };
}

function ensureUpdaterConfig(tauriConf, updaterConfig) {
  tauriConf.plugins ??= {};
  tauriConf.plugins.updater ??= {};
  const endpoints = Array.isArray(tauriConf.plugins.updater.endpoints)
    ? tauriConf.plugins.updater.endpoints
    : [];
  if (endpoints.length === 1 && endpoints[0] === updaterConfig.endpoint) return false;
  tauriConf.plugins.updater.endpoints = [updaterConfig.endpoint];
  return true;
}

function generatedUpdaterSource(updaterConfig) {
  return `// This file is generated by scripts/sync-version.js. Do not edit by hand.
export const updaterConfig = ${JSON.stringify(updaterConfig, null, 2)} as const;
`;
}

try {
  // 1. Read version from package.json
  const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf-8'));
  const version = packageJson.version;
  const updaterConfig = resolveUpdaterConfig(packageJson);
  console.log(`Target version from package.json: ${version}`);
  console.log(`Updater endpoint: ${updaterConfig.endpoint}`);

  // 2. Update tauri.conf.json
  const tauriConf = JSON.parse(readFileSync(TAURI_CONF_PATH, 'utf-8'));
  let tauriUpdated = false;
  if (tauriConf.version !== version) {
    tauriConf.version = version;
    tauriUpdated = true;
    console.log(`Updated ${TAURI_CONF_PATH} to ${version}`);
  }
  if (ensureUpdaterConfig(tauriConf, updaterConfig)) {
    tauriUpdated = true;
    console.log(`Updated ${TAURI_CONF_PATH} updater endpoint`);
  }
  if (tauriUpdated) {
    writeFileSync(TAURI_CONF_PATH, JSON.stringify(tauriConf, null, 2) + '\n');
  } else {
    console.log(`${TAURI_CONF_PATH} is already up to date.`);
  }

  // 3. Update generated frontend updater config
  if (writeTextIfChanged(GENERATED_UPDATER_PATH, generatedUpdaterSource(updaterConfig))) {
    console.log(`Updated ${GENERATED_UPDATER_PATH}`);
  } else {
    console.log(`${GENERATED_UPDATER_PATH} is already up to date.`);
  }

  // 4. Update Cargo.toml
  let cargoToml = readFileSync(CARGO_TOML_PATH, 'utf-8');
  // Match version = "x.y.z" exactly at the start of a line (standard for [package] section)
  const cargoVersionRegex = /^version\s*=\s*"[^"]+"/m;
  
  if (cargoToml.match(cargoVersionRegex)) {
    const currentCargoEntry = cargoToml.match(cargoVersionRegex)[0];
    const newCargoEntry = `version = "${version}"`;
    
    if (currentCargoEntry !== newCargoEntry) {
      cargoToml = cargoToml.replace(cargoVersionRegex, newCargoEntry);
      writeFileSync(CARGO_TOML_PATH, cargoToml);
      console.log(`Updated ${CARGO_TOML_PATH} to ${version}`);
    } else {
      console.log(`${CARGO_TOML_PATH} is already up to date.`);
    }
  } else {
    console.warn(`Could not find version key in ${CARGO_TOML_PATH}`);
  }

  console.log('Version sync complete!');
} catch (error) {
  console.error('Error syncing versions:', error);
  process.exit(1);
}
