export type ProviderPreset = {
  id: string;
  label: string;
  providerId: string;
  providerName: string;
  baseUrl: string;
  model: string;
  badge: string;
  detail: string;
  tags?: string[];
  website?: string;
  custom?: boolean;
};

export const DEFAULT_MODEL = 'gpt-5.5';
export const DEFAULT_PROVIDER_ID = 'custom';
export const DEFAULT_PROVIDER_NAME = 'Custom API';

export const providerPresets: ProviderPreset[] = [
  {
    id: 'custom',
    label: '自定义 API',
    providerId: DEFAULT_PROVIDER_ID,
    providerName: DEFAULT_PROVIDER_NAME,
    baseUrl: '',
    model: DEFAULT_MODEL,
    badge: '手动',
    detail: '保留空 Base URL，适合直接粘贴任意 OpenAI 兼容网关。',
    tags: ['手动', 'OpenAI 兼容', '不保存 Key'],
  },
  {
    id: 'openai',
    label: 'OpenAI 官方',
    providerId: 'openai',
    providerName: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    model: DEFAULT_MODEL,
    badge: '官方',
    detail: '适合 OpenAI/Codex 官方兼容接口；API Key 仍只写入分身账号。',
    tags: ['官方', 'Responses', 'Codex'],
    website: 'https://platform.openai.com/docs',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    providerId: 'openrouter',
    providerName: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    model: 'openai/gpt-5.5',
    badge: '聚合',
    detail: '参考 CC Switch 的 provider preset 思路，快速填入常用聚合网关。',
    tags: ['聚合', 'OpenAI 兼容', '多模型'],
    website: 'https://openrouter.ai/docs',
  },
  {
    id: 'local-ollama',
    label: '本地 Ollama',
    providerId: 'local-ollama',
    providerName: 'Local Ollama',
    baseUrl: 'http://127.0.0.1:11434/v1',
    model: 'gpt-oss',
    badge: '本地',
    detail: '参考 EchoBird 的本地模型入口，方便分身连接本机 OpenAI 兼容服务。',
    tags: ['本地', '离线', '无需云端'],
    website: 'https://ollama.com',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    providerId: 'deepseek',
    providerName: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    model: 'deepseek-chat',
    badge: '国内',
    detail: '常用国内 OpenAI 兼容入口；如果使用推理模型，可在创建前改成对应 reasoning 版本。',
    tags: ['国内', 'OpenAI 兼容', '推理'],
    website: 'https://api-docs.deepseek.com',
  },
  {
    id: 'moonshot-kimi',
    label: 'Moonshot / Kimi',
    providerId: 'moonshot',
    providerName: 'Moonshot AI',
    baseUrl: 'https://api.moonshot.cn/v1',
    model: 'moonshot-v1-8k',
    badge: '国内',
    detail: 'Kimi/Moonshot 兼容入口；模型名按账号开通情况调整。',
    tags: ['国内', 'Kimi', 'OpenAI 兼容'],
    website: 'https://platform.moonshot.cn/docs',
  },
  {
    id: 'dashscope-qwen',
    label: 'DashScope / Qwen',
    providerId: 'dashscope',
    providerName: 'DashScope',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    model: 'qwen-plus',
    badge: '国内',
    detail: '阿里云百炼 OpenAI 兼容模式；适合通义千问/Qwen 系列。',
    tags: ['国内', 'Qwen', 'OpenAI 兼容'],
    website: 'https://help.aliyun.com/zh/model-studio',
  },
  {
    id: 'siliconflow',
    label: 'SiliconFlow',
    providerId: 'siliconflow',
    providerName: 'SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn/v1',
    model: 'Qwen/QwQ-32B',
    badge: '国内',
    detail: '硅基流动 OpenAI 兼容入口；适合按需切换开源模型。',
    tags: ['国内', '开源模型', 'OpenAI 兼容'],
    website: 'https://docs.siliconflow.cn',
  },
  {
    id: 'zhipu-glm',
    label: 'Zhipu / GLM',
    providerId: 'zhipu',
    providerName: 'Zhipu AI',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    model: 'glm-4-plus',
    badge: '国内',
    detail: '智谱 GLM OpenAI 兼容入口；模型名可按控制台列表替换。',
    tags: ['国内', 'GLM', 'OpenAI 兼容'],
    website: 'https://open.bigmodel.cn/dev/howuse/model',
  },
  {
    id: 'tencent-hunyuan',
    label: 'Tencent Hunyuan',
    providerId: 'hunyuan',
    providerName: 'Tencent Hunyuan',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    model: 'hunyuan-turbos-latest',
    badge: '国内',
    detail: '腾讯混元 OpenAI 兼容入口；适合已有腾讯云账号的分身。',
    tags: ['国内', '云厂商', 'OpenAI 兼容'],
    website: 'https://cloud.tencent.com/document/product/1729',
  },
  {
    id: 'baidu-qianfan',
    label: 'Baidu Qianfan',
    providerId: 'qianfan',
    providerName: 'Baidu Qianfan',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    model: 'ernie-4.5-turbo-32k',
    badge: '国内',
    detail: '百度千帆 OpenAI 兼容入口；模型名按千帆控制台开通项调整。',
    tags: ['国内', '文心', 'OpenAI 兼容'],
    website: 'https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html',
  },
  {
    id: 'google-gemini-openai',
    label: 'Google Gemini',
    providerId: 'google-gemini',
    providerName: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    model: 'gemini-2.5-pro',
    badge: '官方',
    detail: 'Gemini 的 OpenAI 兼容入口；仅填表，不安装额外运行时。',
    tags: ['官方', 'Gemini', 'OpenAI 兼容'],
    website: 'https://ai.google.dev/gemini-api/docs/openai',
  },
  {
    id: 'groq',
    label: 'Groq',
    providerId: 'groq',
    providerName: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    model: 'openai/gpt-oss-20b',
    badge: '聚合',
    detail: '高速推理网关；适合临时测试开源模型或轻量分身。',
    tags: ['聚合', '开源模型', 'OpenAI 兼容'],
    website: 'https://console.groq.com/docs',
  },
  {
    id: 'together-ai',
    label: 'Together AI',
    providerId: 'together',
    providerName: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    model: 'openai/gpt-oss-20b',
    badge: '聚合',
    detail: '开源模型聚合入口；可按 Together 控制台模型列表替换。',
    tags: ['聚合', '开源模型', 'OpenAI 兼容'],
    website: 'https://docs.together.ai',
  },
  {
    id: 'perplexity',
    label: 'Perplexity',
    providerId: 'perplexity',
    providerName: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    model: 'sonar-pro',
    badge: '聚合',
    detail: '适合需要搜索增强模型的分身；具体能力以账号权限为准。',
    tags: ['聚合', '搜索增强', 'OpenAI 兼容'],
    website: 'https://docs.perplexity.ai',
  },
  {
    id: 'xai-grok',
    label: 'xAI Grok',
    providerId: 'xai',
    providerName: 'xAI',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-4',
    badge: '官方',
    detail: 'xAI 的 OpenAI 兼容入口；模型名可在 xAI 控制台调整。',
    tags: ['官方', 'Grok', 'OpenAI 兼容'],
    website: 'https://docs.x.ai',
  },
  {
    id: 'azure-openai',
    label: 'Azure OpenAI',
    providerId: 'azure-openai',
    providerName: 'Azure OpenAI',
    baseUrl: 'https://{resource}.openai.azure.com/openai/v1',
    model: DEFAULT_MODEL,
    badge: '云厂商',
    detail: '占位模板：使用前把 {resource} 改成自己的 Azure OpenAI 资源名。',
    tags: ['云厂商', '官方', 'OpenAI 兼容'],
    website: 'https://learn.microsoft.com/azure/ai-services/openai',
  },
  {
    id: 'newapi-gateway',
    label: 'NewAPI / 自部署网关',
    providerId: 'newapi',
    providerName: 'NewAPI Gateway',
    baseUrl: '',
    model: DEFAULT_MODEL,
    badge: '自部署',
    detail: '参考 cc-switch 的统一提供商模板，给 NewAPI、OneAPI 或私有中转预留 Base URL。',
    tags: ['自部署', '聚合', '多协议'],
    website: 'https://github.com/Calcium-Ion/new-api',
  },
];
